# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0001_initial'),
    ]

    operations = [

    ]
