# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
