# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160815_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.AddField(
            model_name='descriptions',
            name='courses',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
