# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160815_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptions',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Descriptions',
        ),
    ]
