# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20160815_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default='description', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
