# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0001_initial'),
        ('courses', '0005_auto_20160815_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginandreg.User'),
            preserve_default=False,
        ),
    ]
