# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20160817_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
