# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
    ]
